# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('landmark', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AgentReferal',
            fields=[
                ('referal_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('verified', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('foreign_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('media_id', models.AutoField(primary_key=True, serialize=False)),
                ('media_type', models.CharField(blank=True, max_length=3, null=True)),
                ('image', models.ImageField(upload_to='medias/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=11)),
                ('iam_name', models.CharField(max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tagent2.Media')),
                ('contactinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tagent2.ContactInfo')),
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
                ('experence', models.IntegerField()),
                ('agent_notes', models.TextField()),
            ],
            bases=('tagent2.contactinfo', 'tagent2.media'),
        ),
        migrations.AddField(
            model_name='location',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagent2.Agent'),
        ),
        migrations.AddField(
            model_name='agentreferal',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagent2.Agent'),
        ),
        migrations.AddField(
            model_name='address',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagent2.Agent'),
        ),
    ]
